theme: jekyll-theme-minimal
title: Kohei MAKINO
description: "<p>Hi. I'm a master student of Toyote Technological Institute.</p> <p>Major: Conputer Science, AI, Natural Language Processing, Relation Extraction, Information Extraction</p> <p>EMAIL: bear.kohei[at]gmail.com</p>"
image: profile_image.jpg