theme: jekyll-theme-minimal
title: Kohei MAKINO
description: "<p>牧野 晃平</p><p>Hi. I'm a master student of Toyota Technological Institute.</p><p>e-mail: sd19446[at]toyota-ti.ac.jp</p>"
logo: img/profile_image.jpg
google_analytics: UA-177329932-1
plugins:
 - jekyll-sitemap
