theme: jekyll-theme-architect
title: Kohei MAKINO
# description: "<p>Hi. I'm a master student of Toyota Technological Institute.</p>"
logo: images/profile_image.jpg
google_analytics: UA-177329932-1
plugins:
    - jekyll-sitemap
linkedin: https://www.linkedin.com/in/kohei-makino/
scholar: https://scholar.google.com/citations?user=SVObobAAAAAJ
