theme: jekyll-theme-architect
title: Kohei MAKINO
description: "<p>牧野 晃平</p><p>Hi. I'm a master student of Toyota Technological Institute.</p><p>e-mail: sd19446[at]toyota-ti.ac.jp</p>"
logo: img/profile_image.jpg
google_analytics: UA-177329932-1
plugins:
    - jekyll-sitemap
linkedin: https://www.linkedin.com/in/kohei-makino/
scholar: https://scholar.google.com/citations?user=SVObobAAAAAJ