theme: jekyll-theme-architect
title: Kohei MAKINO
description: "This page introduces Kohei Makino in Computational Intelligence Laboratory in Toyota Technological Institute in Japan."
logo: images/profile_image.jpg
google_analytics: UA-177329932-1
plugins:
    - jekyll-sitemap
linkedin: https://www.linkedin.com/in/kohei-makino/
scholar: https://scholar.google.com/citations?user=SVObobAAAAAJ
